server:
  port: 8087
  servlet:
    context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  rabbitmq:
    addresses: amqps://uiunkbop:YdOPpryWSXEGGAVeLk24v_xOnmdlVxm5@moose.rmq.cloudamqp.com/uiunkbop

logging:
  level:
    com.ead: TRACE
    root: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service/ead-course'
  broker:
    exchange:
      userEvent: ead.userevent

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost