server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
