server:
  port: 8087

spring:
  application:
    name: ead-authuser-service
  datasource:
    url: jdbc:postgresql://localhost:5432/authuser
    username: anderson
    password: Senha123
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

logging:
  level:
    com.ead: TRACE
    root: INFO

ead:
  api:
    url:
      course: 'http://ead-course-service'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost